import type { User, Group, Season, Transaction, Dare, Game } from "./types"

export const mockUsers: User[] = [
  {
    id: "user_1",
    username: "DareDevil",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DareDevil",
    createdAt: "2024-01-01",
  },
  {
    id: "user_2",
    username: "LuckyCharm",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=LuckyCharm",
    createdAt: "2024-01-02",
  },
  {
    id: "user_3",
    username: "HighRoller",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=HighRoller",
    createdAt: "2024-01-03",
  },
  {
    id: "user_4",
    username: "CardShark",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=CardShark",
    createdAt: "2024-01-04",
  },
]

export const mockGroups: Group[] = [
  {
    id: "group_1",
    name: "The Degenerates",
    members: ["user_1", "user_2", "user_3"],
    inviteCode: "DEGEN1",
    createdAt: "2024-01-01",
  },
  {
    id: "group_2",
    name: "Friday Night Chaos",
    members: ["user_1", "user_4"],
    inviteCode: "CHAOS2",
    createdAt: "2024-01-15",
  },
]

export const mockSeasons: Season[] = [
  {
    id: "season_1",
    groupId: "group_1",
    name: "Season 3",
    startDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    startingCredits: 1000,
    dares: ["dare_1", "dare_3", "dare_5"],
    status: "active",
    balances: { user_1: 1250, user_2: 890, user_3: 760 },
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "tx_1",
    userId: "user_1",
    groupId: "group_1",
    seasonId: "season_1",
    game: "Blackjack",
    bet: 50,
    payout: 100,
    net: 50,
    timestamp: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: "tx_2",
    userId: "user_1",
    groupId: "group_1",
    seasonId: "season_1",
    game: "Roulette",
    bet: 100,
    payout: 0,
    net: -100,
    timestamp: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: "tx_3",
    userId: "user_1",
    groupId: "group_1",
    seasonId: "season_1",
    game: "Mines",
    bet: 25,
    payout: 75,
    net: 50,
    timestamp: new Date(Date.now() - 180000).toISOString(),
  },
  {
    id: "tx_4",
    userId: "user_1",
    groupId: "group_1",
    seasonId: "season_1",
    game: "Crash",
    bet: 200,
    payout: 400,
    net: 200,
    timestamp: new Date(Date.now() - 240000).toISOString(),
  },
  {
    id: "tx_5",
    userId: "user_1",
    groupId: "group_1",
    seasonId: "season_1",
    game: "Plinko",
    bet: 50,
    payout: 25,
    net: -25,
    timestamp: new Date(Date.now() - 300000).toISOString(),
  },
]

export const mockDares: Dare[] = [
  {
    id: "dare_1",
    title: "The Sock Puppet Show",
    description:
      "Perform a 2-minute dramatic monologue using a sock puppet. The topic: your deepest regrets about this season.",
    category: "creative",
    intensity: "mild",
    indoor: true,
  },
  {
    id: "dare_2",
    title: "Spice Roulette",
    description: "Eat a mystery hot sauce selected by the group. No milk for 5 minutes.",
    category: "food",
    intensity: "spicy",
    indoor: true,
  },
  {
    id: "dare_3",
    title: "The Confessional",
    description: "Record a 60-second video admitting your worst gambling habit to the group chat.",
    category: "social",
    intensity: "medium",
    indoor: true,
  },
  {
    id: "dare_4",
    title: "Public Serenade",
    description: "Sing 'I Will Survive' at full volume in a public place while friends record.",
    category: "social",
    intensity: "spicy",
    indoor: false,
  },
  {
    id: "dare_5",
    title: "The Plank of Shame",
    description: "Hold a plank for 2 minutes while the group reads your worst plays from the ledger.",
    category: "physical",
    intensity: "medium",
    indoor: true,
  },
  {
    id: "dare_6",
    title: "Avatar Makeover",
    description: "Let the winner pick your profile picture for the next season.",
    category: "social",
    intensity: "mild",
    indoor: true,
  },
  {
    id: "dare_7",
    title: "Cold Shower Challenge",
    description: "Take a 3-minute ice cold shower. Video proof required.",
    category: "physical",
    intensity: "spicy",
    indoor: true,
  },
  {
    id: "dare_8",
    title: "The Roast",
    description: "Stand while each group member delivers a 30-second roast of your gaming skills.",
    category: "social",
    intensity: "medium",
    indoor: true,
  },
  {
    id: "dare_9",
    title: "Mystery Meal",
    description: "Eat whatever combination of items the group votes for from a restaurant menu.",
    category: "food",
    intensity: "medium",
    indoor: true,
  },
  {
    id: "dare_10",
    title: "Karaoke Nightmare",
    description: "Sing a song chosen by the group at a karaoke bar. No backing out.",
    category: "social",
    intensity: "nuclear",
    indoor: false,
  },
]

export const mockGames: Game[] = [
  {
    id: "poker",
    name: "Poker Table",
    description: "Texas Hold'em with your squad",
    image: "/poker-cards-chips-neon-green.jpg",
    category: "originals",
  },
  {
    id: "blackjack",
    name: "Blackjack",
    description: "Classic 21. Beat the dealer.",
    image: "/blackjack-cards-casino-neon.jpg",
    category: "originals",
  },
  {
    id: "mines",
    name: "Mines",
    description: "Navigate the grid. Don't blow up.",
    image: "/mines-grid-game-neon-gems.jpg",
    category: "originals",
    isNew: true,
  },
  {
    id: "plinko",
    name: "Plinko",
    description: "Drop it like it's hot.",
    image: "/plinko-balls-pyramid-neon.jpg",
    category: "originals",
  },
  {
    id: "crash",
    name: "Crash",
    description: "Cash out before it crashes.",
    image: "/rocket-crash-graph-neon.jpg",
    category: "originals",
    isNew: true,
  },
  {
    id: "roulette",
    name: "Roulette",
    description: "Spin the wheel of fate.",
    image: "/roulette-wheel-casino-neon.jpg",
    category: "originals",
  },
  {
    id: "wheel",
    name: "Wheel",
    description: "Spin to win big.",
    image: "/fortune-wheel-spinning-neon.jpg",
    category: "originals",
    comingSoon: true,
  },
  {
    id: "tower",
    name: "Tower",
    description: "Climb higher, risk more.",
    image: "/tower-climb-game-neon.jpg",
    category: "originals",
    comingSoon: true,
  },
  {
    id: "limbo",
    name: "Limbo",
    description: "How low can you go?",
    image: "/limbo-bar-game-neon.jpg",
    category: "originals",
    comingSoon: true,
  },
  {
    id: "dice",
    name: "Dice",
    description: "Roll the bones.",
    image: "/dice-rolling-neon-glow.jpg",
    category: "popular",
  },
  {
    id: "all-in-roulette",
    name: "All-in Roulette",
    description: "Group spin. All or nothing.",
    image: "/roulette-group-party-neon.jpg",
    category: "party",
  },
  {
    id: "speed-blackjack",
    name: "Speed Blackjack",
    description: "Fast hands. Faster losses.",
    image: "/blackjack-fast-lightning-neon.jpg",
    category: "party",
    isNew: true,
  },
]
